<?php
// Loading the autoloader generated by composer
require __DIR__.'/../vendor/autoload.php';

// Including the FileWriter Listener
require "FileWriter.php";

// loadinging an example xml to parse
$exampleXml = fopen("food.xml", "r");

// Initializing the Sax Parser and adding a new Listener
$streamParser = new pixi\Xml\Parser\Sax();
$streamParser->dispatcher->addSubscriber(new Example\Listener\FileWriter("FoodInfo.txt"));

// start parsing the food.xml
while(!feof($exampleXml)) {
    $streamParser->parse(fread($exampleXml, 4096));
}

fclose($exampleXml);

echo '<pre>';

$newFp = fopen("FoodInfo.txt", "r");
while(!feof($newFp)) {
    echo fread($newFp, 4096);
}